app: bandwidthcoin-bot
build:
  builder: heroku/buildpacks:20
env:
  NODE_ENV: production
services:
  - ports:
      - port: 8080
    concurrency:
      type: connections
      hard_limit: 25
      soft_limit: 20
    processes:
      - app
